gems:
  - jekyll-seo-tag
title: - Lalu Prasad Lenka | Portfolio
description: - Lalu Prasad Lenka's personal website
url: - lplenka.github.io
author: - Lalu Prasad Lenka
facebook:
         admins: https://www.facebook.com/laluprasad.lenka.3
logo: linu.jpg
social:
  name: Lalu Prasad Lenka
  links:
    - https://www.facebook.com/laluprasad.lenka.3
    - https://www.linkedin.com/in/lalu-prasad-lenka-7561b9127
    - https://plus.google.com/+LaluPrasadLenkawow
    - https://github.com/lplenka
